# Frontend Deployment to S3 + CloudFront
name: Deploy Frontend to S3/CloudFront

on:
  push:
    branches: [main]
    paths: ['client/**']
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_BUCKET: beyondask-frontend-prod
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend for production
        env:
          VITE_API_URL: https://api.beyondask.com
          VITE_APP_NAME: BeyondAsk AI
          VITE_ENVIRONMENT: production
        run: |
          npm run build
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync client/dist/ s3://${{ env.S3_BUCKET }} \
            --delete \
            --cache-control "public,max-age=31536000,immutable" \
            --exclude "*.html" \
            --exclude "service-worker.js"
            
          aws s3 sync client/dist/ s3://${{ env.S3_BUCKET }} \
            --delete \
            --cache-control "public,max-age=0,must-revalidate" \
            --include "*.html" \
            --include "service-worker.js"
          
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Output deployment URL
        run: |
          echo "Frontend deployed successfully!"
          echo "URL: https://${{ env.CLOUDFRONT_DISTRIBUTION_ID }}.cloudfront.net"